import { reportService } from "../../services/report.service.js";
import { $, escapeHTML } from "../../utils/dom.js";
import {
  downloadBlobResponse,
  buildFileName
} from "../../utils/download.js";
import { showToast } from "../../components/toast.js";

const view = document.getElementById("app");

let activeReport = "inventory-summary";
let reportRows = [];
let filters = {
  from_date: "",
  to_date: "",
  status: "",
  risk_level: ""
};

const reportConfig = {
  "inventory-summary": {
    title: "Inventory Summary Report",
    description: "Overview of all inventory stock, value, and status levels.",
    endpoint: reportService.getInventorySummary,
    columns: ["Item", "Category", "Department", "Stock", "Status", "Value"]
  },

  "stockout-risk": {
    title: "Stockout Risk Report",
    description: "High-risk medical items likely to fall below safety stock.",
    endpoint: reportService.getStockoutRiskReport,
    columns: ["Item", "Category", "Risk Level", "Probability", "Current Stock", "Safety Stock"]
  },

  expiry: {
    title: "Expiry Report",
    description: "Medicines and supplies approaching expiry date.",
    endpoint: reportService.getExpiryReport,
    columns: ["Item", "Batch No", "Expiry Date", "Stock", "Department", "Status"]
  },

  predictions: {
    title: "Prediction Report",
    description: "Forecasting records generated by ML prediction services.",
    endpoint: reportService.getPredictionReport,
    columns: ["Item", "Facility", "Prediction Date", "Risk Level", "Confidence", "Model"]
  }
};

function skeletonReports() {
  view.innerHTML = `
    <main class="reports-page">
      <div class="skeleton-box"></div>
      <section class="report-type-grid">
        ${Array.from({ length: 4 }).map(() => `<div class="report-type-card skeleton-card"></div>`).join("")}
      </section>
      <div class="reports-card">
        ${Array.from({ length: 8 }).map(() => `<div class="skeleton-row"></div>`).join("")}
      </div>
    </main>
  `;
}

function formatCurrency(value) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD"
  }).format(Number(value || 0));
}

function badge(value) {
  const map = {
    "In Stock": "badge-success",
    "Low Stock": "badge-warning",
    "Out of Stock": "badge-danger",
    Expired: "badge-muted",
    High: "badge-danger",
    Medium: "badge-warning",
    Low: "badge-success"
  };

  return `<span class="status-badge ${map[value] || "badge-info"}">${escapeHTML(value)}</span>`;
}

function renderHeader() {
  return `
    <section class="reports-title-row">
      <div>
        <h1>Reports & Export Center</h1>
        <p>Generate, review, and export operational reports for inventory, risk, expiry, and predictions.</p>
      </div>
    </section>
  `;
}

function renderReportTypes() {
  return `
    <section class="report-type-grid">
      ${Object.entries(reportConfig).map(([key, config]) => `
        <button 
          class="report-type-card ${activeReport === key ? "active" : ""}"
          data-report-type="${key}">
          <span>${reportIcon(key)}</span>
          <strong>${config.title}</strong>
          <p>${config.description}</p>
        </button>
      `).join("")}
    </section>
  `;
}

function reportIcon(type) {
  const map = {
    "inventory-summary": "📦",
    "stockout-risk": "⚠️",
    expiry: "⏳",
    predictions: "🧠"
  };

  return map[type] || "📄";
}

function renderFilters() {
  return `
    <section class="report-filter-bar">
      <label>
        From Date
        <input id="filterFromDate" type="date" value="${escapeHTML(filters.from_date)}" />
      </label>

      <label>
        To Date
        <input id="filterToDate" type="date" value="${escapeHTML(filters.to_date)}" />
      </label>

      <label>
        Status
        <select id="filterStatus">
          <option value="">All Status</option>
          ${["In Stock", "Low Stock", "Out of Stock", "Expired"].map(status => `
            <option value="${status}" ${filters.status === status ? "selected" : ""}>
              ${status}
            </option>
          `).join("")}
        </select>
      </label>

      <label>
        Risk Level
        <select id="filterRisk">
          <option value="">All Risk</option>
          ${["High", "Medium", "Low"].map(risk => `
            <option value="${risk}" ${filters.risk_level === risk ? "selected" : ""}>
              ${risk}
            </option>
          `).join("")}
        </select>
      </label>

      <div class="report-actions">
        <button id="applyReportFilters" class="primary-btn">
          Apply
        </button>

        <button id="exportCsvBtn" class="secondary-btn">
          Export CSV
        </button>

        <button id="exportPdfBtn" class="secondary-btn">
          Export PDF
        </button>
      </div>
    </section>
  `;
}

function normalizeRows(rows) {
  if (Array.isArray(rows)) return rows;
  if (Array.isArray(rows?.items)) return rows.items;
  if (Array.isArray(rows?.data)) return rows.data;
  return [];
}

function renderTable() {
  const config = reportConfig[activeReport];

  return `
    <section class="reports-card">
      <div class="reports-card-header">
        <div>
          <h2>${config.title}</h2>
          <p>${config.description}</p>
        </div>
      </div>

      <div class="table-wrapper">
        <table class="reports-table">
          <thead>
            <tr>
              ${config.columns.map(col => `<th>${col}</th>`).join("")}
            </tr>
          </thead>

          <tbody>
            ${
              reportRows.length
                ? reportRows.map(row => renderReportRow(row)).join("")
                : `<tr><td colspan="${config.columns.length}" class="empty-row">No report data found</td></tr>`
            }
          </tbody>
        </table>
      </div>
    </section>
  `;
}

function renderReportRow(row) {
  if (activeReport === "inventory-summary") {
    return `
      <tr>
        <td><strong>${escapeHTML(row.name || row.item_name)}</strong></td>
        <td>${escapeHTML(row.category_name || row.category || "-")}</td>
        <td>${escapeHTML(row.department || "-")}</td>
        <td>${row.quantity_on_hand ?? row.stock ?? 0}</td>
        <td>${badge(row.status || "-")}</td>
        <td>${formatCurrency(row.total_value || row.value || 0)}</td>
      </tr>
    `;
  }

  if (activeReport === "stockout-risk") {
    return `
      <tr>
        <td><strong>${escapeHTML(row.name || row.item_name)}</strong></td>
        <td>${escapeHTML(row.category || row.category_name || "-")}</td>
        <td>${badge(row.risk_level || "-")}</td>
        <td>${Number(row.stockout_probability || 0).toFixed(2)}</td>
        <td>${row.current_stock ?? 0}</td>
        <td>${row.safety_stock ?? row.min_stock_level ?? 0}</td>
      </tr>
    `;
  }

  if (activeReport === "expiry") {
    return `
      <tr>
        <td><strong>${escapeHTML(row.name || row.item_name)}</strong></td>
        <td><code>${escapeHTML(row.batch_no || "-")}</code></td>
        <td>${escapeHTML(row.expiry_date || "-")}</td>
        <td>${row.quantity_on_hand ?? row.stock ?? 0}</td>
        <td>${escapeHTML(row.department || "-")}</td>
        <td>${badge(row.status || "Expiring")}</td>
      </tr>
    `;
  }

  return `
    <tr>
      <td><strong>${escapeHTML(row.name || row.item_name)}</strong></td>
      <td>${escapeHTML(row.facility || row.facility_name || "-")}</td>
      <td>${escapeHTML(row.predicted_date || "-")}</td>
      <td>${badge(row.risk_level || "-")}</td>
      <td>${Number(row.confidence || row.stockout_probability || 0).toFixed(2)}</td>
      <td>${escapeHTML(row.model_name || row.model || "-")}</td>
    </tr>
  `;
}

function renderReportsPage() {
  view.innerHTML = `
    <main class="reports-page">
      ${renderHeader()}
      ${renderReportTypes()}
      ${renderFilters()}
      ${renderTable()}
    </main>
  `;

  bindEvents();
}

function bindEvents() {
  document.querySelectorAll("[data-report-type]").forEach(button => {
    button.addEventListener("click", async () => {
      activeReport = button.dataset.reportType;
      await loadReport();
    });
  });

  $("#applyReportFilters").addEventListener("click", async () => {
    filters = {
      from_date: $("#filterFromDate").value,
      to_date: $("#filterToDate").value,
      status: $("#filterStatus").value,
      risk_level: $("#filterRisk").value
    };

    await loadReport();
  });

  $("#exportCsvBtn").addEventListener("click", async () => {
    await exportReport("csv");
  });

  $("#exportPdfBtn").addEventListener("click", async () => {
    await exportReport("pdf");
  });
}

async function loadReport() {
  const config = reportConfig[activeReport];

  view.innerHTML = `
    <main class="reports-page">
      ${renderHeader()}
      ${renderReportTypes()}
      ${renderFilters()}
      <section class="reports-card">
        ${Array.from({ length: 8 }).map(() => `<div class="skeleton-row"></div>`).join("")}
      </section>
    </main>
  `;

  const data = await config.endpoint(cleanFilters(filters));
  reportRows = normalizeRows(data);

  renderReportsPage();
}

function cleanFilters(rawFilters) {
  return Object.fromEntries(
    Object.entries(rawFilters).filter(([, value]) => value)
  );
}

async function exportReport(type) {
  try {
    const response =
      type === "csv"
        ? await reportService.exportCsv(activeReport, cleanFilters(filters))
        : await reportService.exportPdf(activeReport, cleanFilters(filters));

    await downloadBlobResponse(
      response,
      buildFileName(activeReport, type)
    );

    showToast(
      `${type.toUpperCase()} exported successfully`,
      "success"
    );

  } catch (error) {
    showToast(
      `Failed to export ${type.toUpperCase()}`,
      "error"
    );
  }
}

export async function renderReports() {
  skeletonReports();
  await loadReport();
}